// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLayer.Migrations
{
    [DbContext(typeof(StateDbContext))]
    [Migration("20231017024434_Update1")]
    partial class Update1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataLayer.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatePublication")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "A recent study published in a leading medical journal has highlighted the potential health benefits of consuming dark chocolate in moderation. The study found that dark chocolate, when consumed in appropriate amounts, could have a positive impact on heart health and may help reduce the risk of certain cardiovascular diseases.",
                            DatePublication = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "New Research Reveals Surprising Benefits of Chocolate"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Unprecedented rainfall in the coastal regions has led to severe flooding, displacing thousands of residents and causing significant damage to infrastructure. Emergency services are working tirelessly to rescue stranded individuals and provide relief to those affected by this natural disaster.",
                            DatePublication = new DateTime(2023, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Record-Breaking Rainfall Causes Flooding in Coastal Regions"
                        },
                        new
                        {
                            Id = 3,
                            Content = "In a groundbreaking move, a leading technology company has unveiled a cutting-edge virtual reality gaming console, promising an immersive gaming experience like never before. Gamers are eagerly anticipating the release of this next-generation gaming system, which is expected to revolutionize the gaming industry.",
                            DatePublication = new DateTime(2023, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Tech Giant Launches Innovative Virtual Reality Gaming Console"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Archaeologists have unearthed a treasure trove of historic artifacts dating back centuries at an ancient archaeological site. These discoveries shed new light on the cultural and historical practices of the civilization that once thrived in this region, captivating historians and enthusiasts alike.",
                            DatePublication = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Historic Artifacts Discovered in Ancient Ruins"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Raging wildfires in the western regions continue to wreak havoc, destroying vast stretches of forests and threatening wildlife habitats. The uncontrolled spread of the fires has prompted urgent calls for additional firefighting resources and coordinated efforts to contain the infernos.",
                            DatePublication = new DateTime(2023, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Wildfire Devastation Continues to Worsen in Western Regions"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Researchers have made a significant breakthrough in cancer treatment with the development of a novel drug that demonstrates promising results in early-stage clinical trials. This breakthrough offers hope to patients and oncologists, potentially revolutionizing cancer therapies in the near future.",
                            DatePublication = new DateTime(2023, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "New Breakthrough Drug Shows Promise in Cancer Treatment"
                        },
                        new
                        {
                            Id = 7,
                            Content = "A major city has taken a significant step towards sustainability by implementing new transportation initiatives aimed at reducing carbon emissions and promoting eco-friendly commuting options. These efforts align with global goals to combat climate change and create a cleaner, more sustainable urban environment.",
                            DatePublication = new DateTime(2023, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "City Implements Sustainable Transportation Initiatives"
                        },
                        new
                        {
                            Id = 8,
                            Content = "A much-anticipated high-speed train project has encountered unexpected technical challenges, causing delays in its completion. Engineers and project teams are working diligently to address these issues and ensure the successful implementation of this transformative transportation initiative.",
                            DatePublication = new DateTime(2023, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "High-Speed Train Project Faces Delays Due to Technical Challenges"
                        },
                        new
                        {
                            Id = 9,
                            Content = "Marine biologists have made a remarkable discovery in the deep ocean—a previously unknown species of marine life with unique characteristics and behaviors. This finding underscores the importance of continued exploration and research to unlock the mysteries of our oceans and preserve biodiversity.",
                            DatePublication = new DateTime(2023, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Scientists Discover New Species of Marine Life in the Deep Ocean"
                        },
                        new
                        {
                            Id = 10,
                            Content = "Recent shifts in global economic policies have sparked a reaction in financial markets, with fluctuations observed in various sectors. Investors and analysts are closely monitoring the situation, assessing potential impacts and adjusting strategies accordingly to navigate the evolving economic landscape.",
                            DatePublication = new DateTime(2023, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Financial Markets React to Global Economic Policy Changes"
                        },
                        new
                        {
                            Id = 11,
                            Content = "In an unexpected announcement, a well-known celebrity has revealed plans for a comeback tour, delighting fans and generating excitement across the entertainment industry. The tour is expected to showcase new music and provide a memorable experience for devoted followers.",
                            DatePublication = new DateTime(2023, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Prominent Celebrity Announces Surprise Comeback Tour"
                        },
                        new
                        {
                            Id = 12,
                            Content = "Educational authorities have unveiled a comprehensive set of reforms aimed at integrating digital learning into school curricula. The initiatives seek to equip students with essential digital skills and enhance the overall learning experience by leveraging technology in the classroom.",
                            DatePublication = new DateTime(2023, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Education Reforms Aim to Enhance Digital Learning in Schools"
                        },
                        new
                        {
                            Id = 13,
                            Content = "Astronomers have made a groundbreaking discovery—an exoplanet located within the habitable zone of its star, suggesting conditions conducive to liquid water and potential for life. This finding opens up new avenues for the search for extraterrestrial life beyond our solar system.",
                            DatePublication = new DateTime(2023, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Astronomers Discover Exoplanet with Potential for Habitable Conditions"
                        },
                        new
                        {
                            Id = 14,
                            Content = "Residents of a local community joined forces for a successful charity fundraiser, raising substantial funds for a noble cause. The event demonstrated the power of collective action and compassion, leaving a positive impact on the community and those in need.",
                            DatePublication = new DateTime(2023, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Local Community Comes Together for Charity Fundraiser"
                        },
                        new
                        {
                            Id = 15,
                            Content = "An innovative startup focused on clean energy solutions has secured a significant round of funding, propelling their efforts to develop and implement sustainable technologies. The investment reflects a growing commitment to addressing environmental challenges through innovative and sustainable practices.",
                            DatePublication = new DateTime(2023, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Innovative Startup Receives Funding to Develop Clean Energy Solutions"
                        });
                });

            modelBuilder.Entity("DataLayer.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("DataLayer.Entities.FeedBackOrComplains", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatePublication")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("FeedBackOrComplains");

                    b.HasDiscriminator<string>("Discriminator").HasValue("FeedBackOrComplains");
                });

            modelBuilder.Entity("DataLayer.Entities.Good", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GoodType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Goods");
                });

            modelBuilder.Entity("DataLayer.Entities.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("DataLayer.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DataLayer.Entities.FeedBackOrComplains", b =>
                {
                    b.HasOne("DataLayer.Entities.Customer", "Customer")
                        .WithMany("FeedBacks")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DataLayer.Entities.Good", b =>
                {
                    b.HasOne("DataLayer.Entities.Order", "Order")
                        .WithMany("Goods")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DataLayer.Entities.Order", b =>
                {
                    b.HasOne("DataLayer.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DataLayer.Entities.Customer", b =>
                {
                    b.Navigation("FeedBacks");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("DataLayer.Entities.Order", b =>
                {
                    b.Navigation("Goods");
                });
#pragma warning restore 612, 618
        }
    }
}
